# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt install -y --no-install-recommends virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11
    sudo apt install -y --no-install-recommends lubuntu-desktop
  SHELL

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.gui = false
    vb.cpus = 2
  end
end

