# install stuffs
sudo add-apt-repository ppa:klaus-vormweg/awesome
sudo add-apt-repository ppa:kelleyk/emacs
sudo apt-get update

# basic stuffs
sudo apt install stow tmux

# awesomewm
sudo apt install -y awesome awesome-extra

# zsh
# install core zsh shell
sudo apt install zsh -y
chsh -s $(which zsh)
# oh-my-zsh
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
rm ~/.zshrc  # need to remove the default file generated by oh-my-zsh


# emacs
sudo apt install emacs26  # install core emacs, packages will be installed automatically in the first run.

# urxvt
sudo apt install rxvt-unicode -y  # installation
sudo update-alternatives --set x-terminal-emulator /usr/bin/urxvt  # set default terminal emulator

# pip
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py --user

# virtual environment wrapper for python
pip install virtualenvwrapper --user

# make symlinks
stow vim
stow tmux
stow zsh
stow urxvt
stow awesome
stow emacs

